### ISSUE TITLE
Action buttons don't open the app on Android

### ISSUE THREAD

**Issue by KevinWessels** [Artfloriani/LocalNotification#12]
Even with openApp:true the app is only opened when clicking the notification itself, not when clicking the buttons.

**Comment by KevinWessels** [comment]
This might have something to do with it?  

if (notification.getOptions().isOpenApp() && actionIdentifier == null) {
    launchApp();
}

**Comment by Artfloriani** [comment]
You are right. I will change the behaviour to match the READ-ME.

**Comment by KevinWessels** [comment]
That would be great! Ideally actions should have something like the openApp key so we can let one action open the app while another does not (like in a voip app, accept opens the app and joins the call while reject just dismisses the notification).

**Comment by Artfloriani** [comment]
@KevinWessels Sorry about the delay, been quite busy around here. I fixed the `openApp` property and added a `destructive` inside the action. I might 

**openApp** _default: true_
When set to false, the app won't open in any case. When set to true the app will open when tapping the notification or any action which `destructive` is set to false.

**destructive** _default: false_
When set to true, the app will not open when the button is tapped. 

Android support only for now. 
Any suggestions are welcome.
